name: build

on:
  release:
    types:
      [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with: 
          images:
            colemamd/acurite2mqtt
          tags:
            type=semver,pattern={{major}}.{{minor}}
          flavor:
            latest=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - nane: Build and Push
      - uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          